baseURL = "https://drichardson.netlify.com"
languageCode = "en-us"
title = "Dale Richardson"
theme = "minimal"
disqusShortname = "dnrichardson-1" # delete this to disable disqus comments

[params]
    author = "Dale Richardson"
    description = "A space for exploration"
    githubUsername = "dnrichardson"
    accent = "orange"
    showBorder = true
    backgroundColor = "white"
    font = "Droid Sans" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "tomorrow"
    highlightLanguages = ["r"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
    url = "/projects/"
    name = "Projects"
    weight = 3
    
[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 4
    
[[menu.main]]
    url = "/cv/"
    name = "CV"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:dalesan@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/dnrichardson/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/yogiwankinobi/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/dalesan/"
    name = "linkedin"
    weight = 4

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
